### ISSUE TITLE
Increase the link input field width

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#11]
![screen shot 2017-05-14 at 5 49 51 pm](https://cloud.githubusercontent.com/assets/15987931/26038062/c8a7696e-38cd-11e7-9a4b-09ed10091c51.png)

Currently it's fairly short. We have plenty of room now that we moved HubSpot CTA to another CTA Type. Many of the links marketers will use will include tracking parameters, which makes the URL very long. If the field is longer then it will be easier for the user to see the full link.

**Comment by mirshko** [comment]
Should be good now.
