### ISSUE TITLE
Consider rewriting/ changing presentation of the embed tab

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#13]
![screen shot 2017-05-14 at 5 54 01 pm](https://cloud.githubusercontent.com/assets/15987931/26038104/8404f6d6-38ce-11e7-98ed-96ccc30b6a9f.png)

it feels a little overwhelming when we really want to simplify CTAs for our users. It might mean rewording or reorganizing the information on this tab. I will take a stab at it.

**Comment by mirshko** [comment]
Maybe remove the `Alternatively` line? Shorten it up a bit.

**Comment by danieljmurphy91** [comment]
Yes. 

What if you moved that line below the embed code?

**Comment by mirshko** [comment]
<img width="1114" alt="screen shot 2017-05-22 at 5 15 04 pm" src="https://cloud.githubusercontent.com/assets/8116716/26328746/42c82e3c-3f12-11e7-9ef2-2eb27107ccba.png">

Thoughts?

**Comment by danieljmurphy91** [comment]
I do like that better.

**Comment by mirshko** [comment]
Good to close it?
