### ISSUE TITLE
Custom Font Support

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#14]
![screen shot 2017-05-14 at 5 57 54 pm](https://cloud.githubusercontent.com/assets/15987931/26038119/f73fd5a8-38ce-11e7-9504-b2e7fe253479.png)

Currently the fonts input field does work. But we've talked about a couple things. This story covers a few parts of the font input field:

1. The "automatically use my website font" which will mean the embed code does not include a font-family css declaration so the font will be pulled from the website's stylesheet. That seems to basically work now (I added a tool tip description). 

2. If they want to use another font, what fonts can we offer? Can we pull from Google fonts? Can we add an inline css declaration that will define the font type that will actually work on the user's website?

**Comment by mirshko** [comment]
Feature built out, how many other fonts would you like to add?

**Comment by danieljmurphy91** [comment]
Very awesome. 

Okay, what's the best way to organize which fonts we want? What's the limit?

**Comment by mirshko** [comment]
Just a list is fine. There is no limit, just increases load time of the app with how many we want to add. And makes the embed code section even more a mess, not really avoidable though.

**Comment by danieljmurphy91** [comment]
Open Sans
Lato
Indie Flower
Hind
Crimson Text
Roboto Mono
Arial
Proxima Nova
Cambria
Calibri
Times New Roman
Georgia
Impact
Verdana

^^ a few from my list, what do you think? What would you add/remove?

**Comment by mirshko** [comment]
LOOOL I was hoping like 5 at first.

**Comment by mirshko** [comment]
Thats fine though, this can be an on-going improvement.

**Comment by danieljmurphy91** [comment]
We can start with five. But I might want to add one or nine to that... ;)

**Comment by mirshko** [comment]
Works for me 👍

**Comment by mirshko** [comment]
Google Fonts implemented.
