### ISSUE TITLE
Build CTA type: CTA w/ Image

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#17]
@mirshko I know you think we shouldn't do this one, because of the spacing issue. But what if we had the image disappear at like 650px width or something? That way it won't look like crap on smaller devices. I really want to make an attempt on this CTA type because I know marketers will love it (it's a very common CTA style for how today's designed CTAs)

**Comment by danieljmurphy91** [comment]
Moving this to 2.0 Release. Not necessary for BETA.

**Comment by mirshko** [comment]
@danieljmurphy91 check it out ;)
