### ISSUE TITLE
Appears 1000px preview, but jumps to 840px

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#2]
<img width="882" alt="screen shot 2017-05-06 at 9 58 21 pm" src="https://cloud.githubusercontent.com/assets/15987931/25777504/26124118-32ad-11e7-9265-2d0881763a2e.png">

Try dragging the bar to adjust the size. It oddly jumps to 840px then you can't resize to anything larger than 840px.

**Comment by mirshko** [comment]
I found the issue. Will fix

**Comment by mirshko** [comment]
Should be good now.

**Comment by danieljmurphy91** [comment]
confirmed.
