### ISSUE TITLE
Text hover w/ edit icon should be disabled under tabs 2, 3 and 4

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#21]
![screen shot 2017-05-15 at 9 23 45 pm](https://cloud.githubusercontent.com/assets/15987931/26085816/da5e73ae-39b4-11e7-8777-3e13c6693be8.png)

Just need to disable when the user moves on to tab 2, 3, & 4.

**Comment by mirshko** [comment]
Should be fixed now. @danieljmurphy91 close when verified.
