### ISSUE TITLE
Adjust background color of app

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#22]
I'm not a huge fan of the white sections and a white background color. 

I played around with a few variations of light grey. I like: `#f5f5f5` and a bit darker: `#ececec`

@mirshko can you try these out and give me your take?

**Comment by mirshko** [comment]
Im a bigger fan of #fafafa or Material Grey 50.

![Screenshot 2017-05-18 18.55.47](http://static.gitscout.com/38d10132afdfcb19566cdd0969e7e2a969a42542bedd727567a433cbc749b6fe.png)

#f5f5f5 feels too dark

![Screenshot 2017-05-18 18.56.51](http://static.gitscout.com/f1bb0f2774bff5a44cf810dcadafd7a9e3682d3b1b2a5dad43fe04d7440927df.png)

**Comment by mirshko** [comment]
@danieljmurphy91 thoughts?

**Comment by danieljmurphy91** [comment]
I like what's currently live on app.responsivectabuilder.com.

**Comment by mirshko** [comment]
Yeah, im good with it too.
