### ISSUE TITLE
HubSpot CTA code added to the button text

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#3]
HubSpot CTA code added to the button text

Happens when you select the "enable" toggle.
<img width="952" alt="screen shot 2017-05-06 at 10 00 20 pm" src="https://cloud.githubusercontent.com/assets/15987931/25777511/62add56a-32ad-11e7-9b87-5ff189df7d93.png">

**Comment by mirshko** [comment]
So heres the issue. The button text and link will all be set in HubSpot CTA so it makes sense to show it here as what their code will look like. I think however we need to add a Standard - HubSpot option since it wont have the button text or linking section. Just a section to add your CTA ID

**Comment by danieljmurphy91** [comment]
hmm... I'm not sure what you're suggesting. We might need to talk this one through in person. But the way it works today feels like a bug and I'm certain a user would stop at this point thinking the app doesn't work. We either need a workaround or some tooltips to show the user that it IS working...

**Comment by mirshko** [comment]
Yeah its deff a more complicated workflow.

**Comment by mirshko** [comment]
Solved by #15
