### ISSUE TITLE
HubSpot CTA ID back into step 3?

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#30]
![screen shot 2017-05-22 at 7 28 52 pm](https://cloud.githubusercontent.com/assets/15987931/26332498/ee87d378-3f24-11e7-9291-3ca8b12b1322.png)

I'm thinking that having the "HubSpot" cta in the CTA Type dropdown is confusing. 

Is it possible to have the CTA ID below the Link but make it so that it's binary (when one input field has something in it, the other field is greyed out)? 

I'm forgetting why we removed the field from the third step, but it feels unnatural as it's own type. I know we will need good documentation for this part.

**Comment by mirshko** [comment]
I forgot to take this text out oops.

**Comment by mirshko** [comment]
Fixed.
