### ISSUE TITLE
Stage app on beta URL: beta.responsivectabuilder.com 

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#47]
This URL will be where our beta users access the app. We don't want it to be app.responsivectabuilder.com because we might want to yank permissions after the beta testing. This also will let us monitor who is using the app and if we see someone leak it to too many users. We will probably only have 5-7 organizations beta testing our app. 

beta-{{org.name}}.responsivectabuilder.com 

i.e. beta-onshape.responsivectabuilder.com 

This story obviously is something we should do towards the end of wrapping up our beta release.

**Comment by mirshko** [comment]
Able to whitelist app now, no need for company urls
