### ISSUE TITLE
Connect application to Google Analytics (and set any tracking we want).

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#48]
WE not only want to track visits to the app, but also (if possible):

1. How many times CTA code is copied from the app, Step 4. (indicating how many CTAs are created and used).

2. How many sign ins to the app (maybe this is something we can track with AuthoO?)

3. A measurement of how many links have been used in CTAs? (Step 3).

**Comment by mirshko** [comment]
1. is already in Google Analytics and tracked as an event

**Comment by mirshko** [comment]
2. Auth0 has a whole signins dashboard. Ill see if we can push this into Google Analytics, could be fine to just check there though.

**Comment by mirshko** [comment]
3. Like the exact links? Or just how many people have pasted in links to the link form?

**Comment by mirshko** [comment]
@danieljmurphy91 what else do you want on this story?

**Comment by danieljmurphy91** [comment]
Okay, looks like your covered all the important "stats" that I can think of for now.
