### ISSUE TITLE
Top preview button breaks at ~350px width

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#50]
<img width="495" alt="screen shot 2017-06-01 at 6 09 35 pm" src="https://cloud.githubusercontent.com/assets/15987931/26703053/cff46f7e-46f5-11e7-93b9-71e3a3d2074f.png">

**Comment by mirshko** [comment]
This is due to the cta's JS media queries not running as the cta is resized. Need to fix

**Comment by mirshko** [comment]
Fixed as of #61
