### ISSUE TITLE
Transparency slider is perhaps not obvious

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#58]
<img width="1056" alt="screen shot 2017-06-04 at 2 39 51 pm" src="https://cloud.githubusercontent.com/assets/15987931/26764366/c83bcc60-4933-11e7-8d7f-eb3db5b8e71c.png">

There should be an opacity slider similar to the radius button slider. Or a field to input % opaque.

**Comment by danieljmurphy91** [comment]
I just realized there is... but it's in the color picker. It's not obvious. Is there a better UX we can come up with?

**Comment by mirshko** [comment]
I think its rather obvious that its transparency. Would be a good UX test to take note of though.

**Comment by danieljmurphy91** [comment]
It's not that the transparency bar isn't obvious, as much as it feels like adjusting the transparency would be it's own field in the "Style" step (instead of a slider within the image overlay). I definitely could be wrong on this, it could just be me. So you are right, it's good thing to look for in a UX test.
