### ISSUE TITLE
Embed code right margin cut off?

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#59]
<img width="1025" alt="screen shot 2017-06-04 at 2 48 31 pm" src="https://cloud.githubusercontent.com/assets/15987931/26764517/0c763558-4936-11e7-89f3-956b29129697.png">

See screenshot. I tried reloading, recreated this issue a couple times.

**Comment by mirshko** [comment]
Yup, its an issue with the `<code>` block working on a fix

**Comment by mirshko** [comment]
Oops

**Comment by mirshko** [comment]
Should be fixed. 

Submitted a PR to Buefy to fix this issue in the future
