### ISSUE TITLE
Website: install responsive CTA preview on homepage

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#64]
www.responsivectabuilder.com

Add a CTA with a slider to this homepage to someone can build slide the CTA to test it out. 

The form can be right below it. Could you add: first name, last name, email and company name to the form? 
<img width="668" alt="screen shot 2017-06-08 at 5 25 58 pm" src="https://user-images.githubusercontent.com/15987931/26951617-d67a88a4-4c6f-11e7-94ca-d26b91891920.png">
<img width="939" alt="screen shot 2017-06-08 at 5 27 39 pm" src="https://user-images.githubusercontent.com/15987931/26951618-d68c0e1c-4c6f-11e7-8e8e-7cccc2a85d15.png">

**Comment by mirshko** [comment]
Please add this ticket to https://github.com/buildbetterCTAs/www.responsivectabuilder.com
