### ISSUE TITLE
Define character count for ideal headline, secondary text & button text

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#7]
Playing around with different character counts for each text input, decide which length is the maximum a user should be able to enter (so it doesn't ruin the CTA responsively/ look bad).

**Comment by danieljmurphy91** [comment]
I'm thinking:

Headline text: 100 max
Secondary text: 160 max
Button text: 40 max. Current media queries will only allow for 34 character before breaking the button:
![screen shot 2017-05-14 at 5 43 03 pm](https://cloud.githubusercontent.com/assets/15987931/26037999/ccd49954-38cc-11e7-8ffc-8627623a20c5.png)

**Comment by danieljmurphy91** [comment]
The text below the input field should say, "You must keep your text under x characters to assure your CTA looks good on all devices"

**Comment by mirshko** [comment]
So there is another option for the button, to have it increase in height and overflow to another line. It would look like this.

![Screenshot 2017-05-17 21.06.12](http://static.gitscout.com/3c8a01427088a519dc219ecbecbde31e6d13e1311e7bf632d81f517b8c73040b.png)

**Comment by mirshko** [comment]
@danieljmurphy91 thoughts? ^

**Comment by danieljmurphy91** [comment]
Can you make the line-height shorter? Seems like a dramatic gap.

Do you like text on two lines?

**Comment by mirshko** [comment]
Its not great. But for buttons that have to be long. Its the only great option.

**Comment by danieljmurphy91** [comment]
Okay. If you can decrease line-height, then I'm for it.

**Comment by mirshko** [comment]
Something like this?

![Screenshot 2017-05-18 18.48.44](http://static.gitscout.com/82a2cb46e6918291187add24a0c81860ed60ed7abbb01fe45f32197104d792fd.png)

**Comment by danieljmurphy91** [comment]
Much better. But the limit should be 40 characters instead of 60.

**Comment by mirshko** [comment]
I want the limit to be a bit above it to allow for the odd long word to fit.

**Comment by mirshko** [comment]
@danieljmurphy91 would you rather restrict it 100% on the button?

**Comment by mirshko** [comment]
@danieljmurphy91 ?

**Comment by danieljmurphy91** [comment]
I think this is fine as is. Thanks. Closing.
