### ISSUE TITLE
Color Picker not allowing hue slider with hex value of #ffffff

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#75]
![screen shot 2017-06-10 at 12 28 52 pm](https://user-images.githubusercontent.com/15987931/27004531-6f23c1a6-4dd8-11e7-899d-b815acecb7b9.png)

1. Open the app
2. Refresh your browser.
3. Navigate to the style tab and open the color picker for any color input field
4. Try to slide the color slider bar (the bar not the rectangle color picker):
![screen shot 2017-06-10 at 12 32 16 pm](https://user-images.githubusercontent.com/15987931/27004565-ee53e294-4dd8-11e7-9595-3f4ccff35cbd.png)

You cannot adjust the color bar until you've adjusted the color shade in the rectangle:
![screen shot 2017-06-10 at 12 32 12 pm](https://user-images.githubusercontent.com/15987931/27004561-e4573142-4dd8-11e7-9417-1b88adaf7f30.png)

This is a problem with the package I'm assuming? It makes for a bad user experience.

**Comment by mirshko** [comment]
@danieljmurphy91 Cannot replicate.

**Comment by mirshko** [comment]
![kapture 2017-06-11 at 10 31 06](https://user-images.githubusercontent.com/8116716/27011768-1dbeba50-4e91-11e7-886d-1571472b8423.gif)

**Comment by danieljmurphy91** [comment]
Actually it looks like it's only occurring on the Text Color and Button Text Color fields.

**Comment by mirshko** [comment]
Investigating.

**Comment by mirshko** [comment]
Ahh discovered the bug. This is due to pure white #ffffff not having the ability to change the hue so it seems it freaks out and doesn't know what to do. Will report this to the package owner.

**Comment by danieljmurphy91** [comment]
No updates on this, huh?

**Comment by mirshko** [comment]
No its annoying.

**Comment by mirshko** [comment]
https://github.com/xiaokaike/vue-color/issues/39#event-1175073247 Was fixed. Closing
