### ISSUE TITLE
Add automatic width value to bottom preview CTAs

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#8]
Add the width value for the CTA preview on the bottom of the app in the secondary previews. 
![screen shot 2017-05-14 at 5 30 15 pm](https://cloud.githubusercontent.com/assets/15987931/26037882/2c7abc64-38cb-11e7-98ab-ff658349e51c.png)

**Comment by mirshko** [comment]
So the value is currently displayed, just not currently for the top CTA.

**Comment by mirshko** [comment]
It is also not responsive to browser resizing on the bottom yet. Only on load will it update.

**Comment by danieljmurphy91** [comment]
Yeah, I saw that. Will keep this open until the resizing works with the value.

**Comment by mirshko** [comment]
Fixed
