### ISSUE TITLE
Can't see button when adjusting button color input field

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#83]
<img width="1265" alt="screen shot 2017-06-23 at 2 50 30 pm" src="https://user-images.githubusercontent.com/15987931/27496266-644722fa-5823-11e7-859a-fe18a39c20b1.png">

We'll have to conquer this UX issue together. No clearcut solution, might be a UI 2.0 refresh, not sure.

**Comment by mirshko** [comment]
Might be worth seeing if a collapsible element to expand / shrink the styles group for each one might make sense.
