### ISSUE TITLE
Add ability to adjust text alignment for button and cta texts

### ISSUE THREAD

**Issue by mirshko** [buildbetterCTAs/app.responsivectabuilder.com#86]
**User Feedback**: *"Inability to center text and buttons (I get that this is because the button itself stays static, but it would be cool if there was a way around)."*

**Proposed Additions**: Add dropdowns for CTA text and button alignment (center, left, right, justify)

**Comment by mirshko** [comment]
@danieljmurphy91

**Comment by danieljmurphy91** [comment]
I'd rather sit on this for now. Not sure I agree. This is feedback from someone that makes CTAs and centers the text, which might be how he likes to do it, but doesn't necessarily mean it is worth implementing in our product. I also don't want to add too much customization yet. Too many fields/toggles might be overwhelming that this point. @mirshko thoughts?

**Comment by mirshko** [comment]
If we see more requests for this we can add it.
