### ISSUE TITLE
Secondary text with less than 78 characters puts button on same line as secondary text

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#9]
![screen shot 2017-05-14 at 5 38 16 pm](https://cloud.githubusercontent.com/assets/15987931/26037961/386fe930-38cc-11e7-8949-623269977f79.png)

To reproduce:
1. click into the Secondary Text input field. 
2. Start typing. When you reach 78 characters the button jumps to the next line.

**Comment by mirshko** [comment]
Issue fixed, verified in master

<img width="1093" alt="screenshot 2017-05-15 20 51 52" src="https://cloud.githubusercontent.com/assets/8116716/26085203/704a2f7a-39b0-11e7-8d41-b11f0a9e0726.png">

**Comment by danieljmurphy91** [comment]
I second your verification on master. Nice.
