### ISSUE TITLE
why is my hubspot CTA styling breaking my responsive CTA styling?

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#91]
![screen shot 2017-07-05 at 5 48 17 pm](https://user-images.githubusercontent.com/15987931/27886504-5b7234b8-61aa-11e7-923d-2168ec0931d8.png)

The CTA in HubSpot is "link, no style" so I'm not sure why the blue button overrides the yellow button? 

The CTA embed code: 

`<script>function load(e){var t=document.getElementsByTagName("head")[0],n=document.createElement("link");return n.type="text/css",n.rel="stylesheet",n.href=e,t.appendChild(n),n}load('https://unpkg.com/cta.css');</script>
<div class="cta" style="border-radius: 4px; background-image: linear-gradient(rgba(27, 95, 170, 0.76), rgba(27, 95, 170, 0.76)), url('https://cdn2.hubspot.net/hubfs/379003/Blog_Assets/Onshape%20Cyclist%20PMC/image2.jpg?t=1499287544009'); background-color: #0E589A;">
    <div class="ctaHeadline" style="color: #ffffff;">Support Team Onshape's Ride for Cancer Research</div>
    <div class="ctaDescription" style="color: #ffffff;"></div>
    <div class="ctaButton hubl" style="background-color: #FFC20E; color: #ffffff">{{ cta('f7c740c7-ab73-4883-819b-9cdb3d7dd986') }}</div>
</div>`

The HubSpot CTA: https://app.hubspot.com/cta/379003/f7c740c7-ab73-4883-819b-9cdb3d7dd986

**Comment by mirshko** [comment]
<img width="467" alt="screenshot 2017-07-05 22 04 49" src="https://user-images.githubusercontent.com/8116716/27892492-068caf2c-61ce-11e7-8c13-f7f78463a0ba.png">

Human error. No classes should be on the CTA
