### ISSUE TITLE
Embed issue with conflicting css classes

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#92]
Reported by user: Kevin Kononenko

Tweets: https://twitter.com/kevinkononenko/status/882713056987549696

https://twitter.com/kevinkononenko/status/882716228007190529

**Comment by mirshko** [comment]
![image](https://user-images.githubusercontent.com/8116716/27892520-28cff8c8-61ce-11e7-8457-a44fd7e04aae.png)

![image](https://user-images.githubusercontent.com/8116716/27892523-2c69fb6e-61ce-11e7-9545-97d0f1f2b053.png)

**Comment by mirshko** [comment]
This is due to the name of the base embed code being very basic. 

Current base Responsive CTA code class is `.cta`
